#!/usr/bin/env bash

# Get microphone mute status using pactl
IS_MUTED=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -o "yes\|no")

get_icon() {
  if [[ $IS_MUTED == "yes" ]]; then
    echo "󰍭"  # Muted microphone icon
  else
    echo "󰍬"  # Unmuted microphone icon
  fi
}

if [[ "$1" == "--icon" ]]; then
  get_icon
elif [[ "$1" == "--status" ]]; then
  echo "$IS_MUTED"
fi
