#!/usr/bin/env bash

# Get volume using wpctl (WirePlumber)
VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}')
IS_MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q "MUTED" && echo "true" || echo "false")

if [[ "$1" == "--percent" ]]; then
  echo "$VOLUME"
elif [[ "$1" == "--icon" ]]; then
  if [[ $IS_MUTED == "true" ]]; then
      echo -n "󰖁"
  else
    case $VOLUME in
      7[0-9]|8[0-9]|9[0-9]|1[0-9][0-9])
          echo ""
        ;;
      4[0-9]|5[0-9]|6[0-9])
          echo "󰕾"
        ;;
      1[0-9]|2[0-9]|3[0-9])
          echo "󰖀"
        ;;
      [1-9])
          echo ""
        ;;
      *)
          echo "󰖁"
        ;;
    esac
  fi
fi
