#!/usr/bin/env bash

# ----| Vars | ----
export SCRIPT_PATH="$HOME/.config/leftwm"

if [[ $DEBUG == 1 ]]; then
  export THEME_CURRENT="$PWD"
else
  export THEME_CURRENT="$SCRIPT_PATH/themes/current"
fi

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s "$THEME_CURRENT/down" /tmp/leftwm-theme-down

leftwm-command "LoadTheme $THEME_CURRENT/themes.toml"

eww -c "$THEME_CURRENT/eww" open laptop
# eww -c "$THEME_CURRENT/eww" open monitor-DP-1
# eww -c "$THEME_CURRENT/eww" open monitor-DP-2
