#!/usr/bin/env bash

# ----| Vars | ----
export SCRIPT_PATH="$HOME/.config/leftwm"
export THEME_CURRENT="$SCRIPT_PATH/themes/current"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s "$THEME_CURRENT/down" /tmp/leftwm-theme-down

leftwm-command "LoadTheme $THEME_CURRENT/themes.toml"

eww -c "$THEME_CURRENT/eww" open monitor
eww -c "$THEME_CURRENT/eww" open monitor-hdmi
eww -c "$THEME_CURRENT/eww" open laptop-with-dual-monitor
