wallpaper {
    monitor = eDP-1
    path = /home/iperez/Wallpaper/man-near-Torii-gate-wallpaper-gray-temple-wallpaper-landscape.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/iperez/Wallpaper/man-near-Torii-gate-wallpaper-gray-temple-wallpaper-landscape.jpg
    fit_mode = cover
}
